create database jsonData;
use jsonData;
create table users(id int not null primary key auto_increment, name varchar(255), age int, address varchar(255));
insert into users( name, age, address)values("Liam",22,"London"),("Olivia",23,"USA"),
("Noah",24,"France"),
("Emma",25,"India"),
("Oliver",23,"USA"),("Ava",23,"USA"),
("Elijah",21,"France"),
("Charlotte",20,"UAE"),
("William",32,"India"),
("Sophia",31,"France"),
("James",27,"USA"),
("Amelia",28,"UAE"),
("Benjamin",29,"France"),
("Isabella",26,""),
("Lucas",28,"UAE"),
("Mia",20,"USA"),
("Henry",29,""),
("Evelyn",32,"France"),
("Alexander",31,"UAE"),
("Harper",30,"USA"),
("Hari",31,"France"),
("Liam",22,"London"),
("Olivia",23,"USA"),
("Noah",24,"France"),
("Emma",25,"India"),
("Oliver",67,"France"),
("Ava",56,"USA"),
("Elijah",24,"USA"),
("lotte",34,"France"),
("liam",45,"India"),
("phialie",34,"France"),
("mejas",43,"India"),
("elia",23,"UAE"),
("jamin",29,"London"),
("Isa",19,"France"),
("Lufas",34,"London"),
("Milly",23,""),
("Heddy",29,"Chaina"),
("Evel",20,"France"),
("Alexa",21,"UAE"),
("Dyna",22,"UAE"),
("Hariyan",23,"London"),
("Liaman",22,"London"),
("Oliv",23,"USA"),
("Noahi",24,"France"),
("Emmay",25,"Chaina"),
("Oli",26,"India"),
("Alan",28,"Chaina"),
("Elon",28,"Chaina"),
("Charlie",27,"India");
select *from users;
